message : this is spring cloud gate way default
spring:
  cloud:
    gateway:
      routes:
        - id: after_route_02
          predicates:
            - Path=/config-route02
#            change the date for future and see the route will be 404
            - After=2029-01-20T17:42:47.789-07:00[America/Denver]
          uri: https://spring.io
